gitweb:
  container_name: gitweb
  image: 99ft/gitweb
  volumes:
    - ./log/nginx:/var/log/nginx
    - ./repos:/repos
    - ./htpasswd:/htpasswd
    - ./indextext.html:/indextext.html
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./gitweb.conf:/etc/gitweb.conf
  ports:
    - 80:80
  environment:
    - THEME=alternative    # default, alternative
    - HOST=direct          # direct, router
