gitweb:
  container_name: gitweb
  image: 99ft/gitweb
  volumes:
    - ./log/nginx:/var/log/nginx
    - ./repos:/repos
    - ./htpasswd:/htpasswd
    - ./gitweb.conf:/etc/gitweb.conf
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./indextext.html:/usr/share/gitweb/indextext.html
    - ./theme/default:/usr/share/gitweb/static
    #- ./theme/alternative:/usr/share/gitweb/static
  ports:
    - 80:80
