gitweb:
  container_name: gitweb
  image: gitweb
  volumes:
    - ./repos:/repos
    - ./log/nginx:/var/log/nginx
    - ./htpasswd:/htpasswd
    - ./gitweb.conf:/etc/gitweb.conf
    - ./nginx.conf:/etc/nginx/nginx.conf
  ports:
    - 80:80
