gitweb:
  container_name: gitweb
  image: gitweb
  volumes:
    - ./repos:/repos
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./log/nginx:/var/log/nginx
    - ./gitweb.conf:/etc/gitweb.conf
  ports:
    - 80:80
