#!/bin/bash
if [ -z $THEME ]; then
  echo "theme: default"
elif [ $THEME = "default" ]; then
  echo "theme: $THEME"
elif [ $THEME = "alternative" ]; then
  mv /usr/share/gitweb/static /usr/share/gitweb/static.bak
  git clone https://github.com/kogakure/gitweb-theme.git /usr/share/gitweb/static
  echo "theme: $THEME"
else
  echo "unknow theme, set to default"
fi

service fcgiwrap start
#chgrp nginx /var/run/fcgiwrap.socket
#chmod g+w /var/run/fcgiwrap.socket
nginx -g 'daemon off;'
