#!/bin/bash
DIR="/repos"

usage(){
    echo "Usage: rmrepo REPO"
    exit 0
}

rmrepo(){
  	REPO=$DIR/$1.git
  	if [ -d $REPO ]; then
        rm -R $REPO
        echo "$1.git removed"
    fi
}

# no parameters
[[ $# -ne 1 ]] && usage

case "$1" in
    --help)
        usage
        ;;
    -h)
        usage
        ;;
    *)
        rmrepo $1
esac
